homepage:
  path: /
  controller: App\Controller\HomepageController::homepage

login:
  path: /login
  controller: App\Controller\LoginController::login
logout:
  path: /logout
  controller: App\Controller\LoginController::logout